### ISSUE TITLE
这是又重建项目了?

### ISSUE THREAD

**Issue by iso-lib** [281677160/AutoBuild-OpenWrt#1]
可以用了回复下咯
看起来插件包还没有齐全

**Comment by 281677160** [comment]
插件包少啥？我插件包只给我仓库用的，你们要用得懂怎么用才行，我这个仓库就没问题了啊

**Comment by iso-lib** [comment]
> 插件包少啥？我插件包只给我仓库用的，你们要用得懂怎么用才行，我这个仓库就没问题了啊

已编译成功,库确实没问题了
2个自定义文件合成一个了,其他的都跟以前差不多.
只不过有些教程图片是老的,可能新来的会困惑.

**Comment by 281677160** [comment]
呵呵，急啥啊，慢慢来，不伺候大爷了，辛辛苦苦伺候大爷们都一年了，不说感恩啥的，基本的尊重都没啊，心凉，随便搞了，想咋搞就咋搞

**Comment by daysdragon** [comment]
编译不了，定位在整理固件文件夹这里出错，
cd bin和cd targets说找不到目录？

**Comment by 281677160** [comment]
> 编译不了，定位在整理固件文件夹这里出错，
> cd bin和cd targets说找不到目录？

哦，今天修改本地乌班图一键编译文件弄的，应该好了吧，真正测试中

**Comment by daysdragon** [comment]
> > 编译不了，定位在整理固件文件夹这里出错，
> > cd bin和cd targets说找不到目录？
> 
> 哦，今天修改本地乌班图一键编译文件弄的，应该好了吧，真正测试中

昨天试了下 LEDE的没有问题

**Comment by 281677160** [comment]
最新更新 https://github.com/281677160/AutoBuild-OpenWrt
