### ISSUE TITLE
watchcat 插件更新后掉配置

### ISSUE THREAD

**Issue by tossp** [281677160/AutoBuild-OpenWrt#12]
watchcat 更新后会掉配置，导致默认的8.8.8.8一直不通，路由器就反复重启

**Comment by 281677160** [comment]
你说luci-app-watchcat这个插件？这个是源码自带的，如果有问题的话，去源码作者那里提提

**Comment by tossp** [comment]
好的

**Comment by 281677160** [comment]
这插件我在源码那里看了一下，都是几年前没动过的了，如果你编译了出现不兼容情况，或者是源码内核还是其他更新后导致的吧，去源码作者那里反映一下，最好说详细点，重启原因看看内核日志或者系统日志的，自己看不懂可以打包给人家研究的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月23日(周五) 晚上7:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [281677160/AutoBuild-OpenWrt] watchcat 插件更新后掉配置 (#12)




 
Closed #12.
