### ISSUE TITLE
大佬，请问云编译能否增加一个功能，编译成功自动上传到docker仓库

### ISSUE THREAD

**Issue by aliporcins** [281677160/AutoBuild-OpenWrt#13]
这样就可以直接在docker仓库拉取openwrt，然后直接docker搭建openwrt

**Comment by 281677160** [comment]
没用过docker不了解流程



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月24日(周六) 晚上11:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [281677160/AutoBuild-OpenWrt] 大佬，请问云编译能否增加一个功能，编译成功自动上传到docker仓库 (#13)




 
这样就可以直接在docker仓库拉取openwrt，然后直接docker搭建openwrt

**Comment by aliporcins** [comment]
> 没用过docker不了解流程
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月24日(周六) 晚上11:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [281677160/AutoBuild-OpenWrt] 大佬，请问云编译能否增加一个功能，编译成功自动上传到docker仓库 (#13) 这样就可以直接在docker仓库拉取openwrt，然后直接docker搭建openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

https://blog.csdn.net/boling_cavalry/article/details/115476859  这里有个教程 麻烦您看下

**Comment by 281677160** [comment]
> > 没用过docker不了解流程
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2021年7月24日(周六) 晚上11:09 收件人: _**@**_.**_>; 抄送: _**@**_.***>; 主题: [281677160/AutoBuild-OpenWrt] 大佬，请问云编译能否增加一个功能，编译成功自动上传到docker仓库 (#13) 这样就可以直接在docker仓库拉取openwrt，然后直接docker搭建openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> https://blog.csdn.net/boling_cavalry/article/details/115476859 这里有个教程 麻烦您看下

看的头大，用到的文件都是N久之前的，docker都改了不知道多少版了，应该不适用了吧，上传构建好的镜像到https://hub.docker.com还能看出点头绪，用.tar.gz文件构建镜像简直看天书

**Comment by aliporcins** [comment]
好吧
