### ISSUE TITLE
大佬发现LEDE下Samba合Samba4测试使用不了，我都是分开编译的，实际在共享中搜不到Samba这个文件夹

### ISSUE THREAD

**Issue by aliporcins** [281677160/AutoBuild-OpenWrt#14]

**Comment by 281677160** [comment]
源码自带插件，用不了找源码作者，再说你一句用不了，神仙都搞不懂，没什么机型，日志啥都没



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月28日(周三) 晚上6:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [281677160/AutoBuild-OpenWrt] 大佬发现LEDE下Samba合Samba4测试使用不了，我都是分开编译的，实际在共享中搜不到Samba这个文件夹 (#14)

**Comment by aliporcins** [comment]
好的，不好意思又骚扰到你了，大佬~
