### ISSUE TITLE
Lan口如何自定义为DHCP？

### ISSUE THREAD

**Issue by Lintion** [281677160/AutoBuild-OpenWrt#15]
非常感谢大佬的分享，小白我也终于学会可以自定义插件编译自己的固件了。
不过我看自定义里，lan口可以自定义IP，不过我软路由是作为旁路有的，不知道如何自定义为dhcp客户端，让主路由自动分配IP。这样刷机之后，就不用再去修改IP了。

**Comment by 281677160** [comment]
旁路由自定义啥子dhcp啊，不是主路由分配吗？把自定义里面的关闭dhcp打开，编译好了后，openwrt就关闭了dhcp了，自定义里面设置好网关，DNS，不就可以直接上网了？

**Comment by 281677160** [comment]
我那些自定义就是给旁路由准备的，如果是主路由的话，其他不要打开，就设置好后台IP就行了

**Comment by Lintion** [comment]
你好，我的意思是旁路由作为DHCP客户端诶。主路由已经给旁路由的mac绑定了一个IP的，这样主路由能看到旁路由的连接情况。
![image](https://user-images.githubusercontent.com/13412937/127473254-5155b36e-6f64-4906-bb94-ac94d6b288bb.png)

**Comment by 281677160** [comment]
自己看说明呗，把路由器设置好的文件提出来，按路径放files文件夹



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月29日(周四) 晚上6:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [281677160/AutoBuild-OpenWrt] Lan口如何自定义为DHCP？ (#15)




 
你好，我的意思是旁路由作为DHCP客户端诶。主路由已经给旁路由的mac绑定了一个IP的，这样主路由能看到旁路由的连接情况。

**Comment by Lintion** [comment]
OK，好的，非常感谢大佬的回复。
