### ISSUE TITLE
请教如何把ssh链接信息发送到电报机器人

### ISSUE THREAD

**Issue by gztingting** [281677160/AutoBuild-OpenWrt#2]
最近使用action每步更新很慢，甚至有时候卡住，实际每一步都在执行，请教如何将ssh链接信息推送到电报机器人TelegramBot上。相关的token和userid等均已经设置好。

是不是把ssh步骤里加上with：
下面--data 部分该传递什么数据到电报机器人，怎么定义ssh链接信息？

- name: SSH远程连接（配置固件）
      uses: danshui-git/debugger-action@master
              if: env.SSH_ACTIONS == 'true' || (github.event.inputs.ssh == 'ssh' && github.event.inputs.ssh  != 'false')
              env:
                     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
                     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
              with
                        if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
                          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "**text=**" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
                        fi

**Comment by 281677160** [comment]
如何使用电报机器人请看说明，如果你说编译的时候每个步骤都慢的话，你得找github的负责人了，服务器问题，现在的github经常抽风，以前都不需要翻/墙的，现在也需要了，造成很多困扰，我也没办法的，这几天我也在升级定时更新插件的设置，可能会造成编译步骤出错吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/AutoBuild-OpenWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 下午5:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教如何把ssh链接信息发送到电报机器人 (#2)





 
最近使用action每步更新很慢，甚至有时候卡住，实际每一步都在执行，请教如何将ssh链接信息推送到电报机器人TelegramBot上。相关的token和userid等均已经设置好。
 
是不是把ssh步骤里加上with：
 下面--data 部分该传递什么数据到电报机器人，怎么定义ssh链接信息？
  
name: SSH远程连接（配置固件）
 uses: ***@***.***
 if: env.SSH_ACTIONS == 'true' || (github.event.inputs.ssh == 'ssh' &amp;&amp; github.event.inputs.ssh  != 'false')
 env:
 TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
 TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
 with
 if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
 curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
 fi

**Comment by gztingting** [comment]
我是想把ssh链接信息推送给机器人，你之前的说明有详细介绍，但我不会怎么把某一步的信息推送出来，请教

**Comment by 281677160** [comment]
SSH链接信息推送看说明啊，某一步是什么呢？开始跟结束我都写了有代码在说明，自己看呗

**Comment by gztingting** [comment]
> SSH链接信息推送看说明啊，某一步是什么呢？开始跟结束我都写了有代码在说明，自己看呗

我按https://github.com/danshui-git/shuoming/blob/master/bot.md
这个说明把电报机器人都搞好了，有富强环境，编译开始和成功的信息已经能正确推送。

我现在想的是在SSH链接这步，把链接信息推送给机器人。引用你说明里这张图，怎么把35、36行的CLI: SSH XXXXXX URL: XXXXXX的信息传递给机器人：
![SSH信息截图](https://raw.githubusercontent.com/danshui-git/shuoming/master/doc/01.png)

这两行的信息，如何在下面这个--data 后面用变量来传递？
![image](https://user-images.githubusercontent.com/30251020/123020959-c6ca3e00-d405-11eb-95bd-6013ae2758d2.png)

**Comment by 281677160** [comment]
设置好ID跟TOKEN就可以了呗，又不需要你弄啥
