### ISSUE TITLE
请教一下大神 怎么添加第三方插件或者插件包

### ISSUE THREAD

**Issue by Thanf-code** [281677160/AutoBuild-OpenWrt#4]
格式怎么写？比如添加应用过滤插件 地址https://github.com/destan19/OpenAppFilter

**Comment by 281677160** [comment]
这东西我脚本不是自带的吗？不过L大改版后不兼容了，现在不知道兼容不兼容，不兼容的话，选了编译就编译失败了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/AutoBuild-OpenWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 晚上6:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4)





 
格式怎么写？比如添加应用过滤插件 地址https://github.com/destan19/OpenAppFilter

**Comment by starxu1971** [comment]
在diy-part.sh添加下面
git clone https://github.com/destan19/OpenAppFilter package/lean/OpenAppFilter #应用过滤插件

**Comment by 281677160** [comment]
不是说了，源码都自带这个插件了？要添加插件看说明啊，不是有写说明啊

**Comment by starxu1971** [comment]
> 在diy-part.sh添加下面
> git clone https://github.com/destan19/OpenAppFilter package/lean/OpenAppFilter #应用过滤插件

我只是举个例子要添加插件就这么添加而已。

**Comment by Thanf-code** [comment]
> 这东西我脚本不是自带的吗？不过L大改版后不兼容了，现在不知道兼容不兼容，不兼容的话，选了编译就编译失败了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年6月28日(星期一) 晚上6:44 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4) 格式怎么写？比如添加应用过滤插件 地址https://github.com/destan19/OpenAppFilter — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢回复！因为我的ssh连接貌似进不去，就想着自己手动添加

**Comment by Thanf-code** [comment]
> 在diy-part.sh添加下面
> git clone https://github.com/destan19/OpenAppFilter package/lean/OpenAppFilter #应用过滤插件

多谢指点

**Comment by 281677160** [comment]
你都不看说明，就把脚本改的乱78糟，肯定进不去啊，修改SSH连接需要修改.yml文件吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/AutoBuild-OpenWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 晚上7:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4)





  
这东西我脚本不是自带的吗？不过L大改版后不兼容了，现在不知道兼容不兼容，不兼容的话，选了编译就编译失败了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月28日(星期一) 晚上6:44 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4) 格式怎么写？比如添加应用过滤插件 地址https://github.com/destan19/OpenAppFilter — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
感谢回复！因为我的ssh连接貌似进不去，就想着自己手动添加

**Comment by Thanf-code** [comment]
> 你都不看说明，就把脚本改的乱78糟，肯定进不去啊，修改SSH连接需要修改.yml文件吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年6月28日(星期一) 晚上7:43 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4) 这东西我脚本不是自带的吗？不过L大改版后不兼容了，现在不知道兼容不兼容，不兼容的话，选了编译就编译失败了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月28日(星期一) 晚上6:44 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4) 格式怎么写？比如添加应用过滤插件 地址https://github.com/destan19/OpenAppFilter — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 感谢回复！因为我的ssh连接貌似进不去，就想着自己手动添加 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.


> 你都不看说明，就把脚本改的乱78糟，肯定进不去啊，修改SSH连接需要修改.yml文件吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年6月28日(星期一) 晚上7:43 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4) 这东西我脚本不是自带的吗？不过L大改版后不兼容了，现在不知道兼容不兼容，不兼容的话，选了编译就编译失败了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月28日(星期一) 晚上6:44 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4) 格式怎么写？比如添加应用过滤插件 地址https://github.com/destan19/OpenAppFilter — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 感谢回复！因为我的ssh连接貌似进不去，就想着自己手动添加 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我明天科学上网看看说明再试试

**Comment by 281677160** [comment]
> > 你都不看说明，就把脚本改的乱78糟，肯定进不去啊，修改SSH连接需要修改.yml文件吗？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" _**@**_._**>; 发送时间: 2021年6月28日(星期一) 晚上7:43 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4) 这东西我脚本不是自带的吗？不过L大改版后不兼容了，现在不知道兼容不兼容，不兼容的话，选了编译就编译失败了 … ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.>; 发送时间: 2021年6月28日(星期一) 晚上6:44 @.>; @.***>; 主题: [281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4) 格式怎么写？比如添加应用过滤插件 地址https://github.com/destan19/OpenAppFilter — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 感谢回复！因为我的ssh连接貌似进不去，就想着自己手动添加 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > 你都不看说明，就把脚本改的乱78糟，肯定进不去啊，修改SSH连接需要修改.yml文件吗？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" _**@**_._**>; 发送时间: 2021年6月28日(星期一) 晚上7:43 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4) 这东西我脚本不是自带的吗？不过L大改版后不兼容了，现在不知道兼容不兼容，不兼容的话，选了编译就编译失败了 … ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.>; 发送时间: 2021年6月28日(星期一) 晚上6:44 @.>; @.***>; 主题: [281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4) 格式怎么写？比如添加应用过滤插件 地址https://github.com/destan19/OpenAppFilter — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 感谢回复！因为我的ssh连接貌似进不去，就想着自己手动添加 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 我明天科学上网看看说明再试试

github都筑墙了，你没科学上网是怎么在这里提问的？没科学上网SSH连接100%连接不了

**Comment by 281677160** [comment]
> > 在diy-part.sh添加下面
> > git clone https://github.com/destan19/OpenAppFilter package/lean/OpenAppFilter #应用过滤插件
> 
> 我只是举个例子要添加插件就这么添加而已。

呃，哦

**Comment by 281677160** [comment]
github已筑墙，访问网页跟SSH都需要科学上网的，启动编译后就不关你的网络事情

**Comment by Thanf-code** [comment]
> github已筑墙，访问网页跟SSH都需要科学上网的，启动编译后就不关你的网络事情

我这个网络不用科学上网，也能访问github，也能ssh，但有些github网页打不开，就比如你这个仓库我能打开，说明文字也能看见，但就是看不到图片。我也不清楚是咋回事

**Comment by 281677160** [comment]
我现在才看明白，你是靠拉取插件源码到固件源码里面，然后他就可以自动到你编译的固件里面了？呃，这个只是把插件拉到固件源码里面而已，想要什么插件要修改.config或者本地提取.config然后覆盖到云仓库的对应机型里面，我的说明就有一个本地一键提取.config的命令

**Comment by Thanf-code** [comment]
> 我现在才看明白，你是靠拉取插件源码到固件源码里面，然后他就可以自动到你编译的固件里面了？呃，这个只是把插件拉到固件源码里面而已，想要什么插件要修改.config或者本地提取.config然后覆盖到云仓库的对应机型里面，我的说明就有一个本地一键提取.config的命令

我本地没有安装乌班图系统，所有提取不了.config。可以通过拉取插件源码到固件源码里，然后到.config里添加相应luci-app-xxx 编译进入吗？

**Comment by 281677160** [comment]
你会写就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月28日(周一) 晚上9:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4)




  
我现在才看明白，你是靠拉取插件源码到固件源码里面，然后他就可以自动到你编译的固件里面了？呃，这个只是把插件拉到固件源码里面而已，想要什么插件要修改.config或者本地提取.config然后覆盖到云仓库的对应机型里面，我的说明就有一个本地一键提取.config的命令
  
我本地没有安装乌班图系统，所有提取不了.config。可以通过拉取插件源码到固件源码里，然后到.config里添加相应luci-app-xxx 编译进入吗？

**Comment by Thanf-code** [comment]
> 你会写就可以了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年6月28日(周一) 晚上9:30 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 怎么添加第三方插件或者插件包 (#4) 我现在才看明白，你是靠拉取插件源码到固件源码里面，然后他就可以自动到你编译的固件里面了？呃，这个只是把插件拉到固件源码里面而已，想要什么插件要修改.config或者本地提取.config然后覆盖到云仓库的对应机型里面，我的说明就有一个本地一键提取.config的命令 我本地没有安装乌班图系统，所有提取不了.config。可以通过拉取插件源码到固件源码里，然后到.config里添加相应luci-app-xxx 编译进入吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我知道为啥进不去ssh了，你的网页ssh是进不去的，只能putty进去才行

**Comment by Thanf-code** [comment]
感谢大神及时回复，该问题已解决
