### ISSUE TITLE
请教一下 如何实现如图椭圆标记处界面

### ISSUE THREAD

**Issue by Thanf-code** [281677160/AutoBuild-OpenWrt#6]
![openwrt界面](https://user-images.githubusercontent.com/82493550/123912829-18e40400-d9b0-11eb-9576-052a5eba7023.jpg)

**Comment by 281677160** [comment]
我最新仓库整了个21.02的，你自己去编译测试看看吧，如果不行我也没办法了，我是不折腾官方的源码的，因为我这是放这里给人拉取的，官方的问题实在是太多了，没办法处理的，就21.02都经过天灵修改的，好像也有问题，我试了一次保存配置升级固件后，不能SSH访问了，可能个别的吧

**Comment by Thanf-code** [comment]
> 我最新仓库整了个21.02的，你自己去编译测试看看吧，如果不行我也没办法了，我是不折腾官方的源码的，因为我这是放这里给人拉取的，官方的问题实在是太多了，没办法处理的，就21.02都经过天灵修改的，好像也有问题，我试了一次保存配置升级固件后，不能SSH访问了，可能个别的吧

感谢大神 辛苦付出   我试试看

**Comment by 281677160** [comment]
> > 我最新仓库整了个21.02的，你自己去编译测试看看吧，如果不行我也没办法了，我是不折腾官方的源码的，因为我这是放这里给人拉取的，官方的问题实在是太多了，没办法处理的，就21.02都经过天灵修改的，好像也有问题，我试了一次保存配置升级固件后，不能SSH访问了，可能个别的吧
> 
> 感谢大神 辛苦付出 我试试看

不用客气，官方源码是给大神弄的，我一个代码都看不懂，我是没能力上官方源码的了，这些源码如果有问题，是可以去源码仓库跟作者提问的，当然你要确定是源码问题才行，如果真的源码有问题，找源码作者还是能解决事情的，如果是官方的，可能沟通都是个问题

**Comment by Thanf-code** [comment]
> > > 我最新仓库整了个21.02的，你自己去编译测试看看吧，如果不行我也没办法了，我是不折腾官方的源码的，因为我这是放这里给人拉取的，官方的问题实在是太多了，没办法处理的，就21.02都经过天灵修改的，好像也有问题，我试了一次保存配置升级固件后，不能SSH访问了，可能个别的吧
> > 
> > 
> > 感谢大神 辛苦付出 我试试看
> 
> 不用客气，官方源码是给大神弄的，我一个代码都看不懂，我是没能力上官方源码的了，这些源码如果有问题，是可以去源码仓库跟作者提问的，当然你要确定是源码问题才行，如果真的源码有问题，找源码作者还是能解决事情的，如果是官方的，可能沟通都是个问题

反馈两个小问题
1.lede 和lienol内核版本切换不了。lede内核始终是5.4，lienol内核版本始终是4.14
2.lede 未开启奶牛快传，但编译出来却有奶牛快传链接

**Comment by 281677160** [comment]
呃，我编译出来怎么没有奶牛快传？这个真没试过没开也有的啊，修改内核要看对应的机型有没有双内核，有才有选择，有选择的时候要修改我本身代码的路径，我的默认是X86路径，查看机型对应内核文件夹在源码的target/linux/架构，在架构的文件夹内查看有几个 patches-x.x 的文件，有的话有什么版本的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/AutoBuild-OpenWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 晚上10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下 如何实现如图椭圆标记处界面 (#6)





    
我最新仓库整了个21.02的，你自己去编译测试看看吧，如果不行我也没办法了，我是不折腾官方的源码的，因为我这是放这里给人拉取的，官方的问题实在是太多了，没办法处理的，就21.02都经过天灵修改的，好像也有问题，我试了一次保存配置升级固件后，不能SSH访问了，可能个别的吧
  
感谢大神 辛苦付出 我试试看
  
不用客气，官方源码是给大神弄的，我一个代码都看不懂，我是没能力上官方源码的了，这些源码如果有问题，是可以去源码仓库跟作者提问的，当然你要确定是源码问题才行，如果真的源码有问题，找源码作者还是能解决事情的，如果是官方的，可能沟通都是个问题
  
反馈两个小问题
 1.lede 和lienol内核版本切换不了。lede内核始终是5.4，lienol内核版本始终是4.14
 2.lede 未开启奶牛快传，但编译出来却有奶牛快传链接

**Comment by Thanf-code** [comment]
> 呃，我编译出来怎么没有奶牛快传？这个真没试过没开也有的啊，修改内核要看对应的机型有没有双内核，有才有选择，有选择的时候要修改我本身代码的路径，我的默认是X86路径，查看机型对应内核文件夹在源码的target/linux/架构，在架构的文件夹内查看有几个 patches-x.x 的文件，有的话有什么版本的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年6月30日(星期三) 晚上10:27 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下 如何实现如图椭圆标记处界面 (#6) 我最新仓库整了个21.02的，你自己去编译测试看看吧，如果不行我也没办法了，我是不折腾官方的源码的，因为我这是放这里给人拉取的，官方的问题实在是太多了，没办法处理的，就21.02都经过天灵修改的，好像也有问题，我试了一次保存配置升级固件后，不能SSH访问了，可能个别的吧 感谢大神 辛苦付出 我试试看 不用客气，官方源码是给大神弄的，我一个代码都看不懂，我是没能力上官方源码的了，这些源码如果有问题，是可以去源码仓库跟作者提问的，当然你要确定是源码问题才行，如果真的源码有问题，找源码作者还是能解决事情的，如果是官方的，可能沟通都是个问题 反馈两个小问题 1.lede 和lienol内核版本切换不了。lede内核始终是5.4，lienol内核版本始终是4.14 2.lede 未开启奶牛快传，但编译出来却有奶牛快传链接 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我的设备是新路由3  架构是ramips  我去源码里面查了一下 lede有5.4和5.10，lienol只有4.14

**Comment by 281677160** [comment]
有双内核你想改就改啊，架构文件夹里面有个Makefile文件的，查看KERNEL_PATCHVER:=x.x 就知道源码默认用的是什么内核呗，修改内核我不是写了一个代码了?把代码的路径修改好，对应的什么改什么设置好不就可以了？
比如你的架构是ramips，源码默认是用5.4内核的，你要改5.10的就改呗
我原本的代码是：sed -i 's/PATCHVER:=5.10/PATCHVER:=5.4/g' target/linux/x86/Makefile

修改对应的内核，修改对应的架构路径，不就可以了

sed -i 's/PATCHVER:=5.4/PATCHVER:=5.10/g' target/linux/ramips/Makefile

**Comment by Thanf-code** [comment]
> 有双内核你想改就改啊，架构文件夹里面有个Makefile文件的，查看KERNEL_PATCHVER:=x.x 就知道源码默认用的是什么内核呗，修改内核我不是写了一个代码了?把代码的路径修改好，对应的什么改什么设置好不就可以了？
> 比如你的架构是ramips，源码默认是用5.4内核的，你要改5.10的就改呗
> 我原本的代码是：sed -i 's/PATCHVER:=5.10/PATCHVER:=5.4/g' target/linux/x86/Makefile
> 
> 修改对应的内核，修改对应的架构路径，不就可以了
> 
> sed -i 's/PATCHVER:=5.4/PATCHVER:=5.10/g' target/linux/ramips/Makefile

是我没有注意到路径修改   改了再编译试试

**Comment by 281677160** [comment]
源码默认内核就为最好的，修改内核不一定好用

**Comment by Thanf-code** [comment]
> 源码默认内核就为最好的，修改内核不一定好用

只是尝试看看

**Comment by Thanf-code** [comment]
> > > 我最新仓库整了个21.02的，你自己去编译测试看看吧，如果不行我也没办法了，我是不折腾官方的源码的，因为我这是放这里给人拉取的，官方的问题实在是太多了，没办法处理的，就21.02都经过天灵修改的，好像也有问题，我试了一次保存配置升级固件后，不能SSH访问了，可能个别的吧
> > 
> > 
> > 感谢大神 辛苦付出 我试试看
> 
> 不用客气，官方源码是给大神弄的，我一个代码都看不懂，我是没能力上官方源码的了，这些源码如果有问题，是可以去源码仓库跟作者提问的，当然你要确定是源码问题才行，如果真的源码有问题，找源码作者还是能解决事情的，如果是官方的，可能沟通都是个问题

编译出来确实是这个界面，但跟其他openwrt系统不太一样。cpu使用率很高，也没有交换机选项，接口设置也变了。设置pppoe但上不了网

**Comment by 281677160** [comment]
> > > > 我最新仓库整了个21.02的，你自己去编译测试看看吧，如果不行我也没办法了，我是不折腾官方的源码的，因为我这是放这里给人拉取的，官方的问题实在是太多了，没办法处理的，就21.02都经过天灵修改的，好像也有问题，我试了一次保存配置升级固件后，不能SSH访问了，可能个别的吧
> > > 
> > > 
> > > 感谢大神 辛苦付出 我试试看
> > 
> > 
> > 不用客气，官方源码是给大神弄的，我一个代码都看不懂，我是没能力上官方源码的了，这些源码如果有问题，是可以去源码仓库跟作者提问的，当然你要确定是源码问题才行，如果真的源码有问题，找源码作者还是能解决事情的，如果是官方的，可能沟通都是个问题
> 
> 编译出来确实是这个界面，但跟其他openwrt系统不太一样。cpu使用率很高，也没有交换机选项，接口设置也变了。设置pppoe但上不了网

交换机这个东西早就没有了，好像要自己在lan那里设置，上不了网就要看看自己有没有设置错误，CPU使用率高的这个问题你可以到源码作者那里反映下

**Comment by Thanf-code** [comment]
> > > > > 我最新仓库整了个21.02的，你自己去编译测试看看吧，如果不行我也没办法了，我是不折腾官方的源码的，因为我这是放这里给人拉取的，官方的问题实在是太多了，没办法处理的，就21.02都经过天灵修改的，好像也有问题，我试了一次保存配置升级固件后，不能SSH访问了，可能个别的吧
> > > > 
> > > > 
> > > > 感谢大神 辛苦付出 我试试看
> > > 
> > > 
> > > 不用客气，官方源码是给大神弄的，我一个代码都看不懂，我是没能力上官方源码的了，这些源码如果有问题，是可以去源码仓库跟作者提问的，当然你要确定是源码问题才行，如果真的源码有问题，找源码作者还是能解决事情的，如果是官方的，可能沟通都是个问题
> > 
> > 
> > 编译出来确实是这个界面，但跟其他openwrt系统不太一样。cpu使用率很高，也没有交换机选项，接口设置也变了。设置pppoe但上不了网
> 
> 交换机这个东西早就没有了，好像要自己在lan那里设置，上不了网就要看看自己有没有设置错误，CPU使用率高的这个问题你可以到源码作者那里反映下

1.cpu使用率高：作者让开启网络加速模块，但我要用应用过滤插件，应用过滤与加速模块冲突
2.设置：wan设置pppoe  显示未连接

**Comment by 281677160** [comment]
网络加速那个是插件来的，你不是可以不选择吗？你说的显示未连接这个问题我就不太清楚了，我是x86旁路由，我测试的时候是可以上网的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/AutoBuild-OpenWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下 如何实现如图椭圆标记处界面 (#6)





      
我最新仓库整了个21.02的，你自己去编译测试看看吧，如果不行我也没办法了，我是不折腾官方的源码的，因为我这是放这里给人拉取的，官方的问题实在是太多了，没办法处理的，就21.02都经过天灵修改的，好像也有问题，我试了一次保存配置升级固件后，不能SSH访问了，可能个别的吧
  
感谢大神 辛苦付出 我试试看
  
不用客气，官方源码是给大神弄的，我一个代码都看不懂，我是没能力上官方源码的了，这些源码如果有问题，是可以去源码仓库跟作者提问的，当然你要确定是源码问题才行，如果真的源码有问题，找源码作者还是能解决事情的，如果是官方的，可能沟通都是个问题
  
编译出来确实是这个界面，但跟其他openwrt系统不太一样。cpu使用率很高，也没有交换机选项，接口设置也变了。设置pppoe但上不了网
  
交换机这个东西早就没有了，好像要自己在lan那里设置，上不了网就要看看自己有没有设置错误，CPU使用率高的这个问题你可以到源码作者那里反映下
  
1.cpu使用率高：作者让开启网络加速模块，但我要用应用过滤插件，应用过滤与加速模块冲突
 2.设置：wan设置pppoe  显示未连接
